version: '3.4'

services:
  gamebox:
    image: node:10.14.1-alpine
    ports:
      - '4600:80'
    volumes:
      - .:/app:rw
    entrypoint:
      - sh
      - /app/entrypoint.sh
    environment:
      - NODE_ENV=dev
  gamebox-react:
    image: node:10.14.1-alpine
    ports:
      - '4700:3000'
    entrypoint:
      - sh
      - /app/entrypoint-react.sh
    volumes:
      - .:/app:rw
    environment:
      - NODE_ENV=dev